package msg

import "github.com/cgalvisleon/et/envar"

var (
	MSG_ATRIB_REQUIRED                 = "required attribute (%s)"
	MSG_FAILED_TO_UNMARSHAL_JSON_VALUE = "failed to unmarshal JSON value:%s"
	MSG_NOT_CACHE_SERVICE              = "caching service not available"
	MSG_RECORD_NOT_FOUND               = "record not found"
	MSG_TOKEN_INVALID                  = "token invalid"
	MSG_TOKEN_INVALID_ATRIB            = "token invalid, attribute (%s)"
	MSG_TOKEN_EXPIRED                  = "token expired"
	MSG_REQUIRED_INVALID               = "request invalid"
	MSG_ERR_INVALID_CLAIM              = "formato token invalid"
	MSG_ERR_AUTORIZATION               = "invalid authorization"
	MSG_ERR_NOT_CONNECT                = "not connect"
	MSG_ERR_CHANNEL_REQUIRED           = "channel required"
	MSG_PACKAGE_NOT_FOUND              = "package not found"
	MSG_METHOD_NOT_FOUND               = "method not found"
	MSG_ERR_PACKAGE_NOT_FOUND          = "package not found"
	MSG_ERR_METHOD_NOT_FOUND           = "method not found"
	MSG_KEY_REQUIRED                   = "key required"
	MSG_CACHE_NOT_LOAD                 = "caching service not available"
	MSG_SOLVER_NOT_BUILD               = "solver not build path:%s"
	MSG_PATH_INVALID                   = "path:%s is invalid"
	MSG_SOLVER_NOT_FOUND_TAG           = "solver:%s not found tag:%s"
	MSG_SOLVER_NOT_FOUND               = "solver:%s not found"
	MSG_METHOD_NOT_SUPPORTED           = "method %s not supported"
	MSG_RESOLVE_NOT_VALID              = "resolve %s is not valid"
	MSG_ARG_REQUIRED                   = "argument required (%s)"
	MSG_CHANNEL_NOT_FOUND              = "channel not found (%s)"
	MSG_USER_NOT_FOUND                 = "user not found (%s)"
	MSG_HOLA                           = "Hello"
	MSG_HUB_NOT_STARTED                = "hub not started"
	MSG_TCP_LISTENING                  = "tcp listening on:%s"
	MSG_TCP_CONNECTED_TO               = "tcp connected to:%s"
	MSG_TCP_CONNECTED_FROM             = "tcp connected from:%s"
	MSG_TCP_CONNECTED_CLIENT           = "tcp connected client:%s"
	MSG_TCP_DISCONNECTED               = "tcp disconnected to:%s"
	MSG_TCP_DISCONNECTED_CLIENT        = "tcp disconnected client:%s"
	MSG_TCP_INBOX                      = "inbox:%s"
	MSG_TCP_RECEIVED                   = "received:%s"
	MSG_TCP_ERROR_READ                 = "error to read:%v"
	MSG_TCP_CLIENT_CLOSED              = "client close connection:%s"
	MSG_TCP_CLIENT_NOT_FOUND           = "client not found:%s"
	MSG_TCP_CLIENT_NOT_CONNECTED       = "client not connected:%s"
	MSG_TCP_SERVER_CLOSED              = "server close connection"
	MSG_TCP_MESSAGE_TOO_LARGE          = "message too large"
	MSG_TCP_TIMEOUT                    = "timeout waiting response"
	MSG_TCP_SHUTTING_DOWN              = "tcp shutting down"
	MSG_TCP_BECAME_LEADER              = "node %s became leader term=%d"
	MSG_TCP_CHANGED_LEADER             = "changed leader term:%d to:%s"
	MSG_SERVICE_REQUIRED               = "service required"
	MSG_INVALID_METHOD                 = "invalid method: %s"
	MSG_INDEX_OUT_OF_RANGE             = "index out of range"
	MSG_SEND_TO                        = "send: %s to:%s"
	MSG_RESPONSE_TO                    = "response: %s to:%s"
	MSG_FIELD_NOT_FOUND                = "field not found"
	MSG_DATA_NOT_FOUND                 = "data not found"
	MSG_TRANSACTION_NOT_FOUND          = "transaction not found"
	MSG_MODEL_NOT_FOUND                = "model not found"
	MSG_MODEL_CONFIG_NOT_FOUND         = "model config not found"
	MSG_CRONTAB_UNLOAD                 = "crontab unloaded"
	MSG_STRING_REQUIRED                = "atribute %s must be string"
	MSG_STRING_NOT_EMPTY               = "atribute %s cannot be empty"
	MSG_INT_REQUIRED                   = "atribute %s must be int"
	MSG_INT_MIN                        = "atribute %s must be >= %d"
	MSG_INT_MAX                        = "atribute %s must be <= %d"
	MSG_FLOAT_REQUIRED                 = "atribute %s must be float"
	MSG_FLOAT_MIN                      = "atribute %s must be >= %f"
	MSG_FLOAT_MAX                      = "atribute %s must be <= %f"
	MSG_ARRAY_REQUIRED                 = "atribute %s must be array"
	MSG_ARRAY_NOT_EMPTY                = "atribute %s cannot be empty"
	MSG_EMAIL_INVALID                  = "atribute %s must be valid email"
	MSG_DATE_INVALID                   = "atribute %s must have format %s"
	MSG_ENUM_INVALID                   = "atribute %s value invalid"
	MSG_NUMBER_REQUIRED                = "atribute %s must be numeric"
	MSG_NUMBER_BETWEEN                 = "atribute %s must be between %v and %v"
	MSG_OBJECT_REQUIRED                = "atribute %s must be object"
	MSG_PHONE_INVALID                  = "atribute %s must be a valid mobile phone number (E.164 format, e.g., +573001234567)"
	MSG_AGENT_NOT_FOUND                = "agent %s not found"
	MSG_STORE_REQUIRED                 = "store is required in production mode"
)

func init() {
	lang := envar.GetStr("LANG", "en")

	if lang == "es" {
		MSG_ATRIB_REQUIRED = "atributo requerido (%s)"
		MSG_FAILED_TO_UNMARSHAL_JSON_VALUE = "no se pudo deserializar el JSON value:%s"
		MSG_NOT_CACHE_SERVICE = "no hay servicio de caching"
		MSG_RECORD_NOT_FOUND = "registro no encontrado"
		MSG_TOKEN_INVALID = "token invalido"
		MSG_TOKEN_INVALID_ATRIB = "token invalido, atributo (%s)"
		MSG_TOKEN_EXPIRED = "token expirado"
		MSG_REQUIRED_INVALID = "solicitud invalida"
		MSG_ERR_INVALID_CLAIM = "formato token invalido"
		MSG_ERR_AUTORIZATION = "invalid autorization"
		MSG_ERR_NOT_CONNECT = "no se pudo conectar"
		MSG_ERR_CHANNEL_REQUIRED = "canal requerido"
		MSG_PACKAGE_NOT_FOUND = "paquete no encontrado"
		MSG_METHOD_NOT_FOUND = "metodo no encontrado"
		MSG_ERR_PACKAGE_NOT_FOUND = "paquete no encontrado"
		MSG_ERR_METHOD_NOT_FOUND = "metodo no encontrado"
		MSG_KEY_REQUIRED = "key requerida"
		MSG_CACHE_NOT_LOAD = "caching service not available"
		MSG_SOLVER_NOT_BUILD = "solver no construido path:%s"
		MSG_PATH_INVALID = "path:%s invalido"
		MSG_SOLVER_NOT_FOUND_TAG = "solver:%s no encontrado tag:%s"
		MSG_SOLVER_NOT_FOUND = "solver:%s no encontrado"
		MSG_METHOD_NOT_SUPPORTED = "metodo %s no soportado"
		MSG_RESOLVE_NOT_VALID = "resolve %s no valido"
		MSG_ARG_REQUIRED = "argumento requerido (%s)"
		MSG_CHANNEL_NOT_FOUND = "canal no encontrado (%s)"
		MSG_USER_NOT_FOUND = "usuario no encontrado (%s)"
		MSG_HOLA = "Hola"
		MSG_HUB_NOT_STARTED = "hub not started"
		MSG_TCP_LISTENING = "tcp listening on:%s"
		MSG_TCP_CONNECTED_TO = "tcp connected to:%s"
		MSG_TCP_CONNECTED_FROM = "tcp connected from:%s"
		MSG_TCP_CONNECTED_CLIENT = "tcp connected client:%s"
		MSG_TCP_DISCONNECTED = "tcp disconnected to:%s"
		MSG_TCP_DISCONNECTED_CLIENT = "tcp disconnected client:%s"
		MSG_TCP_INBOX = "inbox:%s"
		MSG_TCP_RECEIVED = "recibido:%s"
		MSG_TCP_ERROR_READ = "error al leer:%v"
		MSG_TCP_CLIENT_CLOSED = "cliente cerró la conexión:%s"
		MSG_TCP_CLIENT_NOT_FOUND = "cliente no encontrado:%s"
		MSG_TCP_CLIENT_NOT_CONNECTED = "cliente no conectado:%s"
		MSG_TCP_SERVER_CLOSED = "servidor cerró la conexión"
		MSG_TCP_MESSAGE_TOO_LARGE = "mensaje demasiado grande"
		MSG_TCP_TIMEOUT = "timeout esperando respuesta"
		MSG_TCP_SHUTTING_DOWN = "tcp shutting down"
		MSG_TCP_BECAME_LEADER = "Node %s became leader term=%d"
		MSG_TCP_CHANGED_LEADER = "Changed leader term:%d to:%s"
		MSG_SERVICE_REQUIRED = "servicio requerido"
		MSG_INVALID_METHOD = "metodo invalido: %s"
		MSG_INDEX_OUT_OF_RANGE = "index fuera de rango"
		MSG_SEND_TO = "enviado: %s a:%s"
		MSG_RESPONSE_TO = "respuesta: %s a:%s"
		MSG_FIELD_NOT_FOUND = "field not found"
		MSG_DATA_NOT_FOUND = "data not found"
		MSG_TRANSACTION_NOT_FOUND = "transacción no encontrada"
		MSG_MODEL_NOT_FOUND = "modelo no encontrado"
		MSG_MODEL_CONFIG_NOT_FOUND = "configuración del modelo no encontrada"
		MSG_CRONTAB_UNLOAD = "crontab unloaded"
		MSG_STRING_REQUIRED = "atributo %s debe ser string"
		MSG_STRING_NOT_EMPTY = "atributo %s no puede estar vacío"
		MSG_INT_REQUIRED = "atributo %s debe ser int"
		MSG_INT_MIN = "atributo %s debe ser >= %d"
		MSG_INT_MAX = "atributo %s debe ser <= %d"
		MSG_FLOAT_REQUIRED = "atributo %s debe ser float"
		MSG_FLOAT_MIN = "atributo %s debe ser >= %f"
		MSG_FLOAT_MAX = "atributo %s debe ser <= %f"
		MSG_ARRAY_REQUIRED = "atributo %s debe ser array"
		MSG_ARRAY_NOT_EMPTY = "atributo %s no puede estar vacío"
		MSG_EMAIL_INVALID = "atributo %s debe ser email válido"
		MSG_DATE_INVALID = "atributo %s debe tener formato %s"
		MSG_ENUM_INVALID = "atributo %s valor inválido"
		MSG_NUMBER_REQUIRED = "atributo %s debe ser numérico"
		MSG_NUMBER_BETWEEN = "atributo %s debe estar entre %v y %v"
		MSG_OBJECT_REQUIRED = "atributo %s debe ser object"
		MSG_PHONE_INVALID = "atributo %s debe ser un número de teléfono móvil válido (formato E.164, ej: +573001234567)"
		MSG_AGENT_NOT_FOUND = "agente %s no encontrado"
		MSG_STORE_REQUIRED = "store es requerido en modo producción"
	}
}
