package workflow

import "github.com/cgalvisleon/et/envar"

var (
	MSG_FLOW_CREATED                = "Flujo definido tag:%s version:%s name:%s"
	MSG_FLOW_NOT_FOUND              = "Flujo no encontrado"
	MSG_FLOW_NOT_INSTANCE           = "Flujo no instanciado"
	MSG_START_WORKFLOW              = "Iniciando el workflow"
	MSG_INSTANCE_ID_REQUIRED        = "Instance id es requerido"
	MSG_INSTANCE_NOT_FOUND          = "Instancia no encontrada"
	MSG_INSTANCE_EXISTS             = "Instancia existe"
	MSG_INSTANCE_FAILED             = "Instancia fallido:%s tag:%s status:%s, step:%d error:%s"
	MSG_INSTANCE_STATUS             = "Instancia:%s tag:%s status:%s, step:%d"
	MSG_INSTANCE_DEBUG              = "Instancia:%s debug:%s"
	MSG_INSTANCE_GOTO               = "Instancia %s tag:%s ir al step:%d %s"
	MSG_INSTANCE_LOAD               = "Instancia load:%s tag:%s currentStep:%d"
	MSG_INSTANCE_ALREADY_DONE       = "Instancia ya finalizada Id:%s"
	MSG_INSTANCE_ALREADY_RUNNING    = "Instancia ya en ejecucion Id:%s"
	MSG_INSTANCE_PENDING            = "Instancia pendiente Id:%s"
	MSG_INSTANCE_CANCEL             = "Instancia cancelada Id:%s"
	MSG_INSTANCE_LOSS               = "Instancia perdida Id:%s"
	MSG_WORKFLOWS_NOT_LOAD          = "workFlows not loaded"
	MSG_ID_REQUIRED                 = "id es requerido"
	MSG_INSTANCE_EXPRESSION_TRUE    = "Resultado de la expresion es true"
	MSG_INSTANCE_EXPRESSION_FALSE   = "Resultado de la expresion es false"
	MSG_INSTANCE_ROLLBACK           = "Esta intentando hacer rollback de un step que no existe"
	MSG_INSTANCE_ROLLBACK_STEP      = "haciendo rollback del step:%d"
	MSG_INSTANCE_STEP_CREATED       = "Definido step:%d name:%s tag:%s"
	MSG_INSTANCE_ROLLBACK_CREATED   = "Definido rollback step:%d name:%s tag:%s"
	MSG_INSTANCE_ROLLBACK_FAILED    = "Rollback Instance:%s tag:%s status:%s, step:%d error:%s"
	MSG_INSTANCE_CONSISTENCY        = "Consistencia definida tag:%s consistency:%s"
	MSG_INSTANCE_RESILIENCE         = "Definida resilencia tag:%s totalAttempts:%d timeAttempts:%s"
	MSG_INSTANCE_IFELSE             = "Definido ifElse step:%d name:%s expresion:%s ? %d : %d tag:%s"
	MSG_INSTANCE_GOTO_USER_DECISION = "Por desicion del usuario"
	MSG_WORKFLOW_DELETE             = "Workflow eliminado tag:%s"
	MSG_WORKFLOW_DONE_INSTANCE      = "Instancia terminada:%s"
	MSG_WORKFLOW_LIMIT_REQUESTS     = "Límite de peticiones alcanzado, el proceso se pondra en espera para ejecusión, instanceId:%s"
	MSG_INSTANCE_RUN                = "Run instance:%s, flow:%s"
	MSG_INSTANCE_EVALUATE           = "error al evaluar expresion:%s, error:%s"
)

func init() {
	lang := envar.GetStr("LANG", "en")

	if lang == "es" {
		MSG_FLOW_CREATED = "Flujo definido tag:%s version:%s name:%s"
		MSG_FLOW_NOT_FOUND = "Flujo no encontrado"
		MSG_FLOW_NOT_INSTANCE = "Flujo no instanciado"
		MSG_START_WORKFLOW = "Iniciando el workflow"
		MSG_INSTANCE_ID_REQUIRED = "Instance id es requerido"
		MSG_INSTANCE_NOT_FOUND = "Instancia no encontrada"
		MSG_INSTANCE_EXISTS = "Instancia existe"
		MSG_INSTANCE_FAILED = "Instancia fallido:%s tag:%s status:%s, step:%d error:%s"
		MSG_INSTANCE_STATUS = "Instancia:%s tag:%s status:%s, step:%d"
		MSG_INSTANCE_DEBUG = "Instancia:%s debug:%s"
		MSG_INSTANCE_GOTO = "Instancia %s tag:%s ir al step:%d %s"
		MSG_INSTANCE_LOAD = "Instancia load:%s tag:%s currentStep:%d"
		MSG_INSTANCE_ALREADY_DONE = "Instancia ya finalizada Id:%s"
		MSG_INSTANCE_ALREADY_RUNNING = "Instancia ya en ejecucion Id:%s"
		MSG_INSTANCE_PENDING = "Instancia pendiente Id:%s"
		MSG_INSTANCE_CANCEL = "Instancia cancelada Id:%s"
		MSG_INSTANCE_LOSS = "Instancia perdida Id:%s"
		MSG_WORKFLOWS_NOT_LOAD = "workFlows not loaded"
		MSG_ID_REQUIRED = "id es requerido"
		MSG_INSTANCE_EXPRESSION_TRUE = "Resultado de la expresion es true"
		MSG_INSTANCE_EXPRESSION_FALSE = "Resultado de la expresion es false"
		MSG_INSTANCE_ROLLBACK = "Esta intentando hacer rollback de un step que no existe"
		MSG_INSTANCE_ROLLBACK_STEP = "haciendo rollback del step:%d"
		MSG_INSTANCE_STEP_CREATED = "Definido step:%d name:%s tag:%s"
		MSG_INSTANCE_ROLLBACK_CREATED = "Definido rollback step:%d name:%s tag:%s"
		MSG_INSTANCE_ROLLBACK_FAILED = "Rollback Instance:%s tag:%s status:%s, step:%d error:%s"
		MSG_INSTANCE_CONSISTENCY = "Consistencia definida tag:%s consistency:%s"
		MSG_INSTANCE_RESILIENCE = "Definida resilencia tag:%s totalAttempts:%d timeAttempts:%s"
		MSG_INSTANCE_IFELSE = "Definido ifElse step:%d name:%s expresion:%s ? %d : %d tag:%s"
		MSG_INSTANCE_GOTO_USER_DECISION = "Por desicion del usuario"
		MSG_WORKFLOW_DELETE = "Workflow eliminado tag:%s"
		MSG_WORKFLOW_DONE_INSTANCE = "Instancia terminada:%s"
		MSG_WORKFLOW_LIMIT_REQUESTS = "Límite de peticiones alcanzado, el proceso se pondra en espera para ejecusión, instanceId:%s"
		MSG_INSTANCE_RUN = "Run instance:%s, flow:%s"
		MSG_INSTANCE_EVALUATE = "error al evaluar expresion:%s, error:%s"
	}
}
