package jsql

import "github.com/cgalvisleon/et/envar"

var (
	MSG_ATRIB_REQUIRED            = "attribute (%s) is required"
	MSG_DB_STORE_IS_NIL           = "model store is nil"
	MSG_CATALOG_NOT_FOUND         = "catalog not found: %s"
	MSG_DB_IS_NIL                 = "database is nil"
	MSG_DB_NOT_FOUND              = "database not found"
	MSG_DRIVER_NOT_FOUND          = "driver not found"
	MSG_INSTANCE_REQUIRED_ID      = "instance required id"
	MSG_INVALID_FROM              = "invalid from: %s"
	MSG_KEYS_REQUIRED             = "keys is required"
	MSG_MODEL_NOT_FOUND           = "model not found: %s"
	MSG_NAME_REQUIRED             = "name is required"
	MSG_REQUIRED_FIELD            = "required field %s"
	MSG_ROLLBACK_ERROR            = "error rolling back transaction: %v"
	MSG_SCHEMA_NOT_FOUND          = "schema not found: %s"
	MSG_SCHEMA_REQUIRED           = "schema is required"
	MSG_SELECTS_REQUIRED          = "selects is required"
	MSG_TO_MODEL_REQUIRED         = "to model is required"
	MSG_AS_REQUIRED_IN_JOIN       = "as is required in join: %s"
	MSG_TO_REQUIRED_IN_JOIN       = "to is required in join: %s"
	MSG_INVALID_TO_IN_JOIN        = "invalid to in join: %s"
	MSG_COLUMN_NAME_REQUIRED      = "column is required in %s"
	MSG_TYPE_COLUMN_REQUIRED      = "type column is required in %s"
	MSG_TYPE_DATA_REQUIRED        = "type data is required in %s"
	MSG_HISTORY_DB_NOT_CONFIGURED = "history db not configured for model %s"
	MSG_DEAD_DB_NOT_CONFIGURED    = "dead db not configured for model %s"
	MSG_UNSUPPORTED_DRIVER        = "unsupported driver: %s"
	MSG_RECORD_NOT_FOUND          = "record not found"
	MSG_STORE_IS_NIL              = "store is nil"
)

func init() {
	lang := envar.GetStr("LANG", "en")

	if lang == "es" {
		MSG_ATRIB_REQUIRED = "atributo (%s) es requerido"
		MSG_DB_STORE_IS_NIL = "store de base de datos es nulo"
		MSG_CATALOG_NOT_FOUND = "catalogo no encontrado: %s"
		MSG_DB_IS_NIL = "base de datos es nula"
		MSG_DB_NOT_FOUND = "base de datos no encontrada"
		MSG_DRIVER_NOT_FOUND = "driver no encontrado"
		MSG_INSTANCE_REQUIRED_ID = "instancia requiere id"
		MSG_INVALID_FROM = "from inválido: %s"
		MSG_KEYS_REQUIRED = "claves son requeridas"
		MSG_MODEL_NOT_FOUND = "modelo no encontrado: %s"
		MSG_NAME_REQUIRED = "nombre es requerido"
		MSG_REQUIRED_FIELD = "campo requerido %s"
		MSG_ROLLBACK_ERROR = "error al hacer rollback de la transacción: %v"
		MSG_SCHEMA_NOT_FOUND = "esquema no encontrado: %s"
		MSG_SCHEMA_REQUIRED = "esquema es requerido"
		MSG_SELECTS_REQUIRED = "selecciones son requeridas"
		MSG_TO_MODEL_REQUIRED = "modelo destino es requerido"
		MSG_AS_REQUIRED_IN_JOIN = "as es requerido en join: %s"
		MSG_TO_REQUIRED_IN_JOIN = "to es requerido en join: %s"
		MSG_INVALID_TO_IN_JOIN = "to inválido en join: %s"
		MSG_COLUMN_NAME_REQUIRED = "columna es requerida en %s"
		MSG_TYPE_COLUMN_REQUIRED = "tipo de columna es requerido en %s"
		MSG_TYPE_DATA_REQUIRED = "tipo de dato es requerido en %s"
		MSG_HISTORY_DB_NOT_CONFIGURED = "base de datos de historial no configurada para el modelo %s"
		MSG_DEAD_DB_NOT_CONFIGURED = "base de datos muerta no configurada para el modelo %s"
		MSG_UNSUPPORTED_DRIVER = "driver no soportado: %s"
		MSG_RECORD_NOT_FOUND = "registro no encontrado"
		MSG_STORE_IS_NIL = "store es nulo"
	}
}
